### ISSUE TITLE
Can't install it in my Minecraft server.

### ISSUE THREAD

**Issue by kiresreggo** [SkriptLang/skript-worldguard#1]
Hey! I am trying to install this Skript addon in my vps and it doesn't load when all plugins are loaded. Can I have any support please?

**Comment by APickledWalrus** [comment]
Hello, this addon is not yet officially "released" or "supported". Because of that, we are not yet accepting issues.

Please feel free to get support at one of the Discord guilds (SkUnity, SkriptChat) linked here: https://github.com/SkriptLang/Skript#relevant-links

You can even tag me if you want (`APickledWalrus#2895`)
